### ISSUE TITLE
SnakeYAML is shaded and pulled in transitively

### ISSUE THREAD

**Issue by wilkinsona** [FasterXML/jackson-dataformat-yaml#31] opened 2015-01-22 14:13 UTC
The pom states that "we will shade SnakeYAML, to simplify deployment, avoid version conflicts", but SnakeYAML is still pulled in as a transitive dependency. It would appear that the code's using the shaded version so the problem's just with the pom.

**Comment by cowtowncoder** [comment] 2015-01-22 19:35
Hmmh. That is not the intent. :)

 I wonder if this is due to refactoring by @benson-basis. Is this with version 2.5.0?

**Comment by wilkinsona** [comment] 2015-01-22 19:43
I was using 2.4.4 when I noticed the problem

**Comment by benson-basis** [comment] 2015-01-22 19:45
The maven-shade-plugin builds a dependency-reduced-pom.xml that removes the transitive dependency, and that should be what ends up deployed. I'm not sure that it ends up in, say, the jar file in the META-INF/maven. Where, exactly, do you see this problem?

**Comment by wilkinsona** [comment] 2015-01-22 19:55
In the published pom. http://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.5.0/jackson-dataformat-yaml-2.5.0.pom, for example.

**Comment by benson-basis** [comment] 2015-01-22 19:57
This may be a side-effect of the tricky mechanism of combining the bundle
plugin and shade. Tatu, in 2.5 we could reopen making a multi-module
project if you really want to fix this.

**Comment by cowtowncoder** [comment] 2015-01-22 20:15
Ok. Let's hold that thought for just a bit -- mostly because I am investigating possibility of using `yamlbeans` instead of `snakeyaml`. That won't change the need of resolution per se, but would complicate branching.
Also, master being 2.6.0-SNAPSHOT, it'd be for 2.6 fwtw.

**Comment by cowtowncoder** [comment] 2015-05-20 06:15
FWIW, while I don't particularly like SnakeYAML at this pint, yamlbeans proved to be equally glacial wrt speed, and while its jar is smaller there isn't any compelling reason to switch.
So we will be based on snakey for now.

**Comment by CodingFabian** [comment] 2016-03-02 00:07
Hi @cowtowncoder I am using dataformat-yaml in OSGi, and I noticed that the shading is also not super nicely solved for OSGi use case.
For example, if you have a parse error, you will be able to `catch (com.fasterxml.jackson.dataformat.yaml.snakeyaml.parser.ParserException e)`- this works in non-OSGi deployments.
In OSGi however, the container will enforce your declaration: `Export-Package: com.fasterxml.jackson.dataformat.yaml;version="2.7.1"`which means that the exception is not exported, and thus considered private to the bundle.

I do not have any great suggestion, except maybe catching them and converting into a YAMLException you do export inside `com.fasterxml.jackson.dataformat.yaml``
Let me know if i can help clarify this problem or I shall raise a separate issue.

**Comment by cowtowncoder** [comment] 2016-03-04 18:03
@CodingFabian I would be interested in better resolving this. First things might be to have a unit test to show-case an example of leakage.

Now: making sure that the main exception is of exported type makes sense anyway (that is, never exposing non-exported exception types). But I wonder what to do about root cause: it is usually good to pass that along... but changing that won't do much good, although I guess if one was to transfer stack trace information, maybe that would be good enough. Message itself, along with original class name, is helpful but perhaps not sufficient.

So I am open to improvement ideas here. OSGi has a few issues with respect to shading; the problem being that while it is not needed or useful for that use case, it is very useful for non-OSGi use cases.

@benson-basis Just an FYI, you may have some ideas/comments as well?

**Comment by benson-basis** [comment] 2016-03-04 18:20
Ideally, on OSGi, we'd not shade, but just depend. As I recall, you were
not an enthusiast for exposing the dependency. Choices are to (1) stop
shading and just have a dependency, or (2) add some more exports to allow
people to deal with the surrounded exceptions, or (3) build the OSGi bundle
unshaded but the regular jar shaded, by building two artifacts.

**Comment by cowtowncoder** [comment] 2016-03-04 18:25
@benson-basis  I think I'd be most interested in having 2 different jars, with different classifiers (if that is the best mechanism available). Something like this is done with JAX-RS module, to include (or not) META-INF for registering format providers.

Removing shading is not something I am interested in, given how it really helps a lot on non-OSGi cases. I am not specifically worried about SnakeYAML as it seems quite stable and there don't seem to be too many issues wrt version compatibility. But there are other cases of shading for Jackson components, so I think it would be good to have a good way of handling shading for non-OSGI users (which AFAIK is vast majority of users).

Then again... if the challenges we face are specifically about SnakeYAML, it is not completely out of question to leave it as a dependency, if other approaches fail.

**Comment by benson-basis** [comment] 2016-03-04 18:33
Classifiers can't differ in dependencies. So they need to have different
artifact-ids. Typically people slap '-osgi' on the end for the OSGI case.

I'm not proposing a general war against shading, just your last option;
just unshade SnakeYAML. If people really need to catch exceptions from in
there, it makes sense to me not to shade even without OSGi. My view is that
if you shade something, you are sure that no one could possibly need to
touch it except through your API.

**Comment by CodingFabian** [comment] 2016-03-04 18:50
@benson-basis "f people really need to catch exceptions from in there, it makes sense to me not to shade even without OSGi"
Well what do you propose? Let the JVM crash on a YAML parsing error? You have to catch it. And then the cached exception is of an unexported type, which is illegal in OSGi.
For OSGi, if you shade, you need to "rewrite" the exception. Which I personally also would like for the non-OSGi case.
I am using jackson-yaml. I do not care if it is snake yaml, and I do not want to interact with the API in a snakeyaml way. The exception however escapes this.

So my proposal is to catch snake exceptions and convert them. But I know this is much more work than just declaring the dependency.

**Comment by cowtowncoder** [comment] 2016-03-04 19:45
@CodingFabian Let's start with what is the easiest thing to do: if you can show a simple test that generates escaping exception, it should be easy to see how the path should work. I think exposing exception exactly as-is is not good no matter what. For specific types it should be possible to convert without problems.

The point about snakeyaml being a private dependency is good one, too; although exposing its types does give more control (on purely theoretical sense), it is wrong kind of leakage.

**Comment by benson-basis** [comment] 2016-03-04 19:48
I agree that the true fix here is for Jackson to catch them there
exceptions in the first instance.

**Comment by CodingFabian** [comment] 2016-03-04 21:40
here a test which fails because the shaded package exception is thrown to the caller
```
public class EscapingException {
  @Test
  public void internalExceptionShouldNotEscape() {
    try {
      new ObjectMapper(new YAMLFactory()).readTree("foo:\nbar: true\n  baz: false");
    } catch (com.fasterxml.jackson.dataformat.yaml.snakeyaml.scanner.ScannerException e) {
      fail("Internal exception type");
    } catch (Exception e) {
      // good
    }
  }
}
```

**Comment by cowtowncoder** [comment] 2016-03-04 21:46
@CodingFabian thanks.

**Comment by cowtowncoder** [comment] 2016-03-09 00:45
One more related note: just realized that the idea of "jackson-dataformat-yaml-osgi" may not fly -- on its own, it might be ok, but there is also the dependency by `jackson-jaxrs-yaml-provider`, where there would be another case of having to double up jars or something else creative.

So in the end it is probably best to remove shading for 2.8. I will bring this up jackson-dev list.

**Comment by cowtowncoder** [comment] 2016-03-12 22:49
As per above note, Exception-replacement added for 2.7.3.

**Comment by cowtowncoder** [comment] 2016-05-19 02:28
As per commit, SnakeYAML is now included as regular dependency, not shaded.

**Closed** 2016-05-19 02:27 UTC
